#!/usr/bin/env python3
print("----")
print("For convenience, 4 dashes will be used to seperate sentences")
print("----")
print("Please Locate TwitterBot.py and use that as the base for your project, thank you!")
print("----")
print("To make your scripts executables, please use the terminal command -> sudo chmod +x replacewithfilename.py")
print("----")
print("I assume no responsibility for your actions in use of these scripts, what you do with them is your decision and responsibility not mine.")
print("----")
